- name: Update
  hosts: pihole_cluster
  become: true
  serial: 1
  ignore_unreachable: false
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  roles:
    - updates
    - pihole
    - status
