dependency:
  name: galaxy

driver:
  name: vagrant

verifier:
  name: ansible

platforms:
  - name: pihole-master
    box: generic/debian12
    memory: 1024
    cpus: 2
    groups:
      - pihole_cluster
      - master
    interfaces:
      - network_name: private_network
        ip: 10.0.20.50

  - name: pihole-backup
    box: generic/debian12
    memory: 1024
    cpus: 2
    groups:
      - pihole_cluster
      - backup
    interfaces:
      - network_name: private_network
        ip: 10.0.20.51

provisioner:
  name: ansible
  env:
    ANSIBLE_VERBOSITY: 1
  playbooks:
    converge: ../../bootstrap-pihole.yaml
  inventory:
    links:
      group_vars: ../../inventory/group_vars
      host_vars: ../../inventory
      hosts: ../../inventory
